### PR TITLE
Features/ios develop

### PR DESCRIPTION
**Pull request by jingcheng1988**

### CODE REVIEW

**Review by dqelong — APPROVED** [review]
API

**Review by dqelong — APPROVED** [review]
repeat

**Review by dqelong — APPROVED** [review]
api

**Review by dqelong — APPROVED** [review]
API

**Review by dqelong — APPROVED** [review]
API

**Review by dqelong — APPROVED** [review]
API

**Review by MXPDS6688 — APPROVED** [review]

**Review by MXPDS6688 — APPROVED** [review]

**Review by msliu3 — APPROVED** [review]

**Review by dqelong — APPROVED** [review]
approve

**Review by qiqiangqq — COMMENTED** [review]
review all changes

**Comment by qiqiangqq** [comment]
approve all changes

**Pull request merged**
